# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nihilith's blog
email: n.nihilith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  이 웹사이트 자료에 대한 저작권은 © 2015 Singu Lee에게 있습니다. 직접 작성한것만요.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nihilith29.github.io" # the base hostname & protocol for your site
//twitter_username: jekyllrb
github_username:  nihilith29

# Build settings
markdown: kramdown
